// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPrQVIIqf6F9sr9Vumuu9i7GXcPfX6rE',
    appId: '1:1084678667684:web:d2870df47690bc667a1531',
    messagingSenderId: '1084678667684',
    projectId: 'mpunk-8fa03',
    authDomain: 'mpunk-8fa03.firebaseapp.com',
    storageBucket: 'mpunk-8fa03.appspot.com',
    measurementId: 'G-PQ7J36H74P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzljohZFeufpKT4BPzZOwoZlBSACf06uc',
    appId: '1:1084678667684:android:7fbdaacec0740f6b7a1531',
    messagingSenderId: '1084678667684',
    projectId: 'mpunk-8fa03',
    storageBucket: 'mpunk-8fa03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDth47nTp-32a38WdPXbjVK5Nn_6pnDg1c',
    appId: '1:1084678667684:ios:5c72dfe396302de67a1531',
    messagingSenderId: '1084678667684',
    projectId: 'mpunk-8fa03',
    storageBucket: 'mpunk-8fa03.appspot.com',
    iosClientId: '1084678667684-2th5q0f7dlbodcuel4lkpgblple0s3kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindPunk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDth47nTp-32a38WdPXbjVK5Nn_6pnDg1c',
    appId: '1:1084678667684:ios:5c72dfe396302de67a1531',
    messagingSenderId: '1084678667684',
    projectId: 'mpunk-8fa03',
    storageBucket: 'mpunk-8fa03.appspot.com',
    iosClientId: '1084678667684-2th5q0f7dlbodcuel4lkpgblple0s3kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindPunk',
  );
}
